---
# vim: sw=4 ts=102 ai

# need firewalld for firewalld module
- name: install firewalld
  yum:
      name: firewalld
      state: present

- name: start firewalld
  systemd:
      name: firewalld
      state: started
      enabled: yes

- name: firewalld services
  firewalld:
      service: "{{ item }}"
      immediate: true
      permanent: true
      state: enabled
  with_items:
      - dhcp
      - tftp
      - dns
      - https
      - http
      - RH-Satellite-6
