---
# sw=2 ts=102 ai

- name: Get enabled repos
  command: "/usr/bin/hammer --output json repository list {{ORG_ID}}"
  register: hammer_output
  changed_when: False
  when: repo_ids is not defined

- name: map repo name/id pair to SAT_MAP
  set_fact:
    ti: "{{ [ item.key, json_map[item.value.1] | default(0)] }}"
  register: tmp
  with_dict: "{{ SAT_MAP }}"
  vars:
    json_map: "{{ dict(hammer_output.stdout | from_json | json_query('[*][Name, Id]')) }}"
  loop_control:
    label: "{{ item.key }}, {{item.value.1}}"
  when: repo_ids is not defined

- name: coerce map list into dictionary
  set_fact:
      repo_ids: "{{ dict(tmp.results | map(attribute='ansible_facts') | map(attribute='ti') | list)  }}"
  when: repo_ids is not defined
