---
# vim: sw=2 ts=102 ai

- name: Ensure default download policy is on_demand
  command: "/usr/bin/hammer settings set --name default_download_policy --value on_demand"
  changed_when: False

- name: Get enabled repos
  command: "/usr/bin/hammer --output json repository list {{ORG}}"
  register: hammer_output
  changed_when: False

- name: Check if our repos are enabled
  set_fact:
    tmp: dummy
  register: repos_list
  changed_when: "item.test not in (hammer_output.stdout | from_json | map(attribute='Name') | list)"
  with_items: "{{ satellite_hammer_repos }}"
  loop_control:
    label: "{{ item.name }}"

- name: enabling repos
  command: "/usr/bin/hammer repository-set enable {{ ORG }} --product='{{ item.item.product }}' {{ (item.item.release == True) | ternary('--releasever='+item.item.release, '') }} --basearch={{ item.item.basearch }} --name='{{ item.item.name }}'"
  when: "{{ item.changed }}"
  with_items: "{{ repos_list.results }}"
  loop_control:
    label: "{{ item.item.name }}"
