# vim: sw=2 ai ts=102
---
- include: clean.yml
  when: vms_clean is defined
  tags: [configure,subscriptions]

- include: certificates.yml
  tags: [configure,certificates]

- include: subscriptions.yml
  when: vms_clean is not defined
  tags: [configure,subscriptions]

- include: mirrors.yml
  when: "(vms_clean is not defined) and (subscription_mirror) and (ansible_pkg_mgr) and (ansible_pkg_mgr == 'yum' )"
  tags: [configure,mirrors]

- include: upgrade.yml
  when: vms_clean is not defined and rhel_updates
  tags: [configure,upgrade]

- include: disks.yml
  when: vms_clean is not defined
  tags: [configure,disks]
